# Generated by Django 2.2.1 on 2019-05-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_teacher'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Courses',
            field=models.ManyToManyField(to='Course.Course'),
        ),
    ]
