# Generated by Django 2.2.1 on 2019-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
