# Generated by Django 2.2.1 on 2019-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
