# Generated by Django 2.2.1 on 2019-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190525_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='number_of_units',
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
