# Generated by Django 2.2.1 on 2019-05-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190528_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
